image: node:16

pages:
  stage: deploy
  before_script:
    - npm install @scope:registry
  script:
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
