image: node:16

pages:
  stage: deploy
  script:
    - npm install @scope:registry
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
