image: node:16

pages:
  stage: deploy
  before_script:
    - npm config set registry https://registry.npmjs.org/
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
